### PR TITLE
fix(side nav): mobile click to close

### LINKED ISSUE #102: small screen/mobile nav bug(s)
Menu open/closes on each link click
bug

Menu closes when you interact with it
bug2

### PR DESCRIPTION
**Pull request by lovemecomputer**
fixes #102

Closes #102 

implements a new `<div>`, which is a sibling to the `<nav>` side nav. this div is invisible and is the click-to-close-nav target (for when a user clicks outside of the overlayed nave to close it). this extra sibling element is necessary to get gatsby to behave properly :)

### CODE REVIEW

**Comment by alisonjoseph** [comment]
@asudoh can you create an issue for us to run through the entire site for a11y w/ DAP. 🙏

**Comment by lovemecomputer** [comment]
@alisonjoseph sorry, i'm having difficulties seeing where this merge conflict is.

**Comment by lovemecomputer** [comment]
@alisonjoseph merge conflict resolved!

@asudoh yeah i would totally be down to look at what @alisonjoseph suggested!

**Comment by lovemecomputer** [comment]
@alisonjoseph eep thanks for that catch! i needed to add in an extra key to the state to track `isMobile`. i used this terminology to match the word `mobile` used elsewhere. like the rest of the state, it is updated after changing pages.

**Comment by alisonjoseph** [comment]
Getting closer! If you start at a small screen and then go larger, or start larger and go smaller then it doesn't behave as expected and will close the nav (or not close the nav) at the wrong size.

**Comment by asudoh** [comment]
@alisonjoseph Sure created: #147

**Comment by lovemecomputer** [comment]
changes implemented!
- media query sets the click-to-close to `display:none` (the width measurement is in 2 places)
- merges latest changes from upstream master

**Pull request merged**
