### PR TITLE
Add shell variations

### LINKED ISSUE #108: UI Shell - Add code samples to website
We need to determine how the best way to display the latest UI Shell code on the website, and which pieces we want to highlight.

http://staging.carbondesignsystem.com/experimental/ui-shell/code 

@joshblack @aledavila

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #108

Adds the following variations to the website

**UI Shell with expanded sidebar** 
**UI Shell with Platform nav visible** 

moves demo overrides styles in to component overrides stylesheet since they are doing the same thing

@joshblack or @aledavila can you confirm that they are showing up correctly

### CODE REVIEW

**Comment by lovemecomputer** [comment]
the text links in the shell (top nav text links, and sidebar text links) lead to a 404 page :(

**Comment by alisonjoseph** [comment]
Yea, I think the links need to be removed or updated in `carbon-components` potentially? @aledavila was going to take a look at this PR hopefully today/tomorrow and might have some more insight 😄

**Comment by aledavila** [comment]
I'll submit an issue for it.

**Comment by alisonjoseph** [comment]
cool I will merge for now and we can update later once shell is updated

**Pull request merged**
