### PR TITLE
fix(styles): separate theme override

### PR DESCRIPTION
**Pull request by asudoh**
Refs #27.

Checkbox position is off with this change somehow - @alisonjoseph great if you have any ideas, thanks!

### CODE REVIEW

**Comment by alisonjoseph** [comment]
This is closer, thank you. What styles are you noticing that are off? the only thing Im seeing is this focus style that shouldn't be there. 
screen shot 2018-09-14 at 11 32 05 am

I wonder if we could use a different prefix for the experimental styles and swap the html also so that the styles don't interfere with each other?

**Comment by asudoh** [comment]
Thank you @alisonjoseph for testing! The root of the issue is that the only ways to fully scope styles are either `<iframe>` or [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot). The former makes UX worse, and the latter is not supported by IE/Edge.

That said, are you suggesting we use a completely different page for experimental vs. stable? If it can be done with Gatsby and you think it’s the way for us to go, I’m all for it! 😉

**Comment by alisonjoseph** [comment]
I think it might be better to keep the code sample as `bx--` because when someone actually goes to use the experimental components they most likely won't be changing the prefix.

**Comment by asudoh** [comment]
Got it @alisonjoseph! Updated the code as such. The prefix is an idea that I just rattled off, but feel free to suggest any alternatives!

**Pull request merged**
